package memelet.droolsesper

import java.util.Map

global Map results

dialect "mvel"

/*
 How do I measure the rate of arrival of events in a given time period per another category?
 
 http://esper.codehaus.org/tutorials/solution_patterns/solution_patterns.html#throughput-2
 
 	select count(*) as cnt from MarketDataEvent.win:time_batch(1 second)
 	group by feed
*/

/*
 5.0.1 does not support 'time_batch', so the best we can do is capture the
 continous count.
  
 Also, 'group by' is not directly supported by Drools. Here it is approximated using
 the accumulator function collectMap (memelet.drools.CollectMapAccumulateFunction).
 However this accumulator is hard coded to return the count of instances as the
 map value, where in Esper the value yield by 'group by' is generic on select clause.
 
 TODO Is there a way for an accumulator function to take multiple arguments?
 This might allow for a more generic accumulator that would be as generic
 as Esper's 'group by'. 
*/

rule "Rate of arrival of events in a given time period per category?"
when
	$rates : Map() from accumulate ( 
    	$e : MarketDataEvent($feed : feed) over window:time(1s), 
    	collectMap($feed))    
then
	results.put("arrivalRates", $rates);
end
